//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCRUDWithLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeID { get; set; }

        [Display(Name = "Employee Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Employee Name Required!!")]
        public string Name { get; set; }

        [Display(Name = "Position")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Position Required!!")]
        public string Position { get; set; }

        [Display(Name = "Office")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Office Required!!")]
        public string Office { get; set; }

        public Nullable<int> Age { get; set; }

        [Display(Name = "Salary")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Salary Required!!")]
        public Nullable<int> Salary { get; set; }
    }
}
